env:
  global:
    # Used for saving generated test datasets. See Notion for details.
    - secure=FTT6C4vhk88L1RKHmUnbTdXdTyjkhoAhtXwYGAvkrrTngU1uJMZeoFeHLqVf/uxQuNssOrEJsQWGrka5OEd1FAAxUuqTmytxRMuz9A6Z4qp5DiMIDyCB9WF5AdY1cb3XQw5GiPc2BWrmBxxRIKporkaND0UBRmyeHDvppjn0uME=
    - APPLICATION=ojs

dist: focal
os: linux
language: php
python:
  - 3.3 # Required by Javascript linter/builder
git:
  # Inhibit automatic submodule checkout
  submodules: false
cache:
  npm: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache
addons:
  chrome: beta
  postgresql: "9.5"
  apt:
    update: true
    packages:
      - libvulkan1
      - libu2f-udev

before_install:
  # MariaDB has conflicts with MySQL, given that Travis includes MySQL by default, we have to uninstall it before installing MariaDB
  - |
    if [[ "$TEST" == "mariadb" ]]; then
      sudo apt-get remove --purge mysql-server mysql-client mysql-common mysql-server-core-* mysql-client-core-*
      sudo apt-get autoremove -y
      sudo apt-get autoclean
      sudo rm -rf /var/lib/mysql/
      sudo rm -rf /etc/mysql/
      sudo apt-get install mariadb-server mariadb-client
    fi
  - if [ -n "$LIBONIG_INSTALL" ]; then sudo apt-get install libonig5; fi
  - ./tools/startSubmodulesTRAVIS.sh
  - npm i g -npm
  - ./lib/pkp/tools/travis/prepare-webserver.sh
  - ./lib/pkp/tools/travis/install-composer-dependencies.sh
  - npm install && npm run build

stages:
  - validate
  - test
  - upgrade

jobs:
  include:
    - stage: test
      env: TEST=pgsql SAVE_BUILD=true
      php: 8.0
    - env: TEST=pgsql
      php: 8.1.0
    - env: TEST=mariadb SAVE_BUILD=true
      php: 8.0
    - env: TEST=mysql SAVE_BUILD=true
      php: 8.1.0
    - env: TEST=mysql LIBONIG_INSTALL=1
      php: 8.2.0
    - env: TEST=pgsql LIBONIG_INSTALL=1
      php: 8.2.0

    - stage: validate
      php: 8.0
      name: "Validate and lint"
      script:
      - |
        npm install
        ./lib/pkp/tools/travis/install-linter.sh
        ./lib/pkp/tools/travis/validate-xml.sh
        ./lib/pkp/tools/buildjs.sh -n
        ./lib/pkp/tools/checkHelp.sh
        ./lib/pkp/tools/travis/validate-json.sh
        npm run lint

    - stage: upgrade
      env: DATASET_BRANCH=stable-3_3_0 TEST=mysql
      php: 8.0
      script:
        - source ./lib/pkp/tools/travis/prepare-tests.sh
        - git clone https://github.com/pkp/datasets
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/files/* files/
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/public/* public/
        - cp datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/config.inc.php .
        - patch -p1 < datasets/upgrade/3_4_0-add-email-config.diff
        - patch -p1 < datasets/upgrade/3_4_0-update-locale.diff
        - ./datasets/tools/dbclient.sh < datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/database.sql
        - php tools/upgrade.php check
        - php tools/upgrade.php upgrade

    - env: DATASET_BRANCH=stable-3_2_1 TEST=mysql
      php: 8.0
      script:
        - source ./lib/pkp/tools/travis/prepare-tests.sh
        - git clone https://github.com/pkp/datasets
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/files/* files/
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/public/* public/
        - cp datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/config.inc.php .
        - patch -p1 < datasets/upgrade/3_4_0-add-email-config.diff
        - patch -p1 < datasets/upgrade/3_4_0-update-locale.diff
        - ./datasets/tools/dbclient.sh < datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/database.sql
        - php tools/upgrade.php check
        - php tools/upgrade.php upgrade

    - env: DATASET_BRANCH=stable-3_2_0 TEST=mysql
      php: 8.0
      script:
        - source ./lib/pkp/tools/travis/prepare-tests.sh
        - git clone https://github.com/pkp/datasets
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/files/* files/
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/public/* public/
        - cp datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/config.inc.php .
        - patch -p1 < datasets/upgrade/3_4_0-add-email-config.diff
        - patch -p1 < datasets/upgrade/3_4_0-update-locale.diff
        - ./datasets/tools/dbclient.sh < datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/database.sql
        - php tools/upgrade.php check
        - php tools/upgrade.php upgrade

    - env: DATASET_BRANCH=3.1.2 TEST=mysql
      php: 8.0
      script:
        - source ./lib/pkp/tools/travis/prepare-tests.sh
        - git clone https://github.com/pkp/datasets
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/files/* files/
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/public/* public/
        - cp datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/config.inc.php .
        - patch -p1 < datasets/upgrade/3_4_0-add-email-config.diff
        - patch -p1 < datasets/upgrade/3_4_0-update-locale.diff
        - ./datasets/tools/dbclient.sh < datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/database.sql
        - php tools/upgrade.php check
        - php tools/upgrade.php upgrade

    - env: DATASET_BRANCH=3.1.1-2 TEST=mysql
      php: 8.0
      script:
        - source ./lib/pkp/tools/travis/prepare-tests.sh
        - git clone https://github.com/pkp/datasets
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/files/* files/
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/public/* public/
        - cp datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/config.inc.php .
        - patch -p1 < datasets/upgrade/3_4_0-add-email-config.diff
        - patch -p1 < datasets/upgrade/3_4_0-update-locale.diff
        - ./datasets/tools/dbclient.sh < datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/database.sql
        - php tools/upgrade.php check
        - php tools/upgrade.php upgrade

    - env: DATASET_BRANCH=3.1.0 TEST=mysql
      php: 8.0
      script:
        - source ./lib/pkp/tools/travis/prepare-tests.sh
        - git clone https://github.com/pkp/datasets
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/files/* files/
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/public/* public/
        - cp datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/config.inc.php .
        - patch -p1 < datasets/upgrade/3_4_0-add-email-config.diff
        - patch -p1 < datasets/upgrade/3_4_0-update-locale.diff
        - ./datasets/tools/dbclient.sh < datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/database.sql
        - php tools/upgrade.php check
        - php tools/upgrade.php upgrade

    - env: DATASET_BRANCH=stable-3_3_0 TEST=pgsql
      php: 8.0
      script:
        - source ./lib/pkp/tools/travis/prepare-tests.sh
        - git clone https://github.com/pkp/datasets
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/files/* files/
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/public/* public/
        - cp datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/config.inc.php .
        - patch -p1 < datasets/upgrade/3_4_0-add-email-config.diff
        - patch -p1 < datasets/upgrade/3_4_0-update-locale.diff
        - ./datasets/tools/dbclient.sh --quiet < datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/database.sql
        - php tools/upgrade.php check
        - php tools/upgrade.php upgrade

    - env: DATASET_BRANCH=stable-3_2_1 TEST=pgsql
      php: 8.0
      script:
        - source ./lib/pkp/tools/travis/prepare-tests.sh
        - git clone https://github.com/pkp/datasets
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/files/* files/
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/public/* public/
        - cp datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/config.inc.php .
        - patch -p1 < datasets/upgrade/3_4_0-add-email-config.diff
        - patch -p1 < datasets/upgrade/3_4_0-update-locale.diff
        - ./datasets/tools/dbclient.sh --quiet < datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/database.sql
        - php tools/upgrade.php check
        - php tools/upgrade.php upgrade

    - env: DATASET_BRANCH=stable-3_2_0 TEST=pgsql
      php: 8.0
      script:
        - source ./lib/pkp/tools/travis/prepare-tests.sh
        - git clone https://github.com/pkp/datasets
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/files/* files/
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/public/* public/
        - cp datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/config.inc.php .
        - patch -p1 < datasets/upgrade/3_4_0-add-email-config.diff
        - patch -p1 < datasets/upgrade/3_4_0-update-locale.diff
        - ./datasets/tools/dbclient.sh --quiet < datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/database.sql
        - php tools/upgrade.php check
        - php tools/upgrade.php upgrade

    - env: DATASET_BRANCH=3.1.0 TEST=pgsql
      php: 8.0
      script:
        - source ./lib/pkp/tools/travis/prepare-tests.sh
        - git clone https://github.com/pkp/datasets
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/files/* files/
        - cp -r datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/public/* public/
        - cp datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/config.inc.php .
        - patch -p1 < datasets/upgrade/3_4_0-add-email-config.diff
        - patch -p1 < datasets/upgrade/3_4_0-update-locale.diff
        - ./datasets/tools/dbclient.sh --quiet < datasets/${APPLICATION}/${DATASET_BRANCH}/${TEST}/database.sql
        - php tools/upgrade.php check
        - php tools/upgrade.php upgrade

script:
  - source ./lib/pkp/tools/travis/prepare-tests.sh
  - ./lib/pkp/tools/travis/run-tests.sh

after_failure:
  - tail -n 500 error.log
  - sudo apt-get install sharutils
  # Outputs only the oldest file found at the screenshots folder due to log limits
  - find cypress/screenshots -type f -printf '%T+\t%p\n' | sort | head -n 1 | cut -f 2 | tar -cz -T - | uuencode /dev/stdout

after_success:
  - head -n 500 error.log
